### ISSUE TITLE
bug: typescript error when using account hoist pattern in wallet clients

### ISSUE THREAD

**Issue by paro-paro** [wevm/viem#1666]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.0.3

### Current Behavior

When using the following hoisting [pattern](https://viem.sh/docs/clients/wallet.html#optional-hoist-the-account), typescript throws when calling the `client.sendTransaction` action (with no account param).

```ts
import { createWalletClient, custom } from 'viem'
import { mainnet } from 'viem/chains'

const [account] = await (window as any).ethereum.request({ method: 'eth_requestAccounts' })

const client = createWalletClient({ 
  account, 
  chain: mainnet,
  transport: custom((window as any).ethereum),
})

const hash = await client.sendTransaction({ // Property 'account' is missing in type...
  // account, 
  to: '0xa5cc3c03994DB5b0d9A5eEdD10CabaB0813678AC',
  value: 1n
})
```

The functionality works as expected, it is just a type issue.

### Expected Behavior

No ts error.

### Steps To Reproduce

I created a stackblitz repro but at the time of writing, stackblitz does not seems to be loading the typescript language server... 

Just create a simple local repro, install viem, copy-paste the above code... IDE will throw the error.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/github-1shhar?file=app.vue

**Comment by tmm** [comment]
This is because `account` in your code is typed as `any`. Works when `account` is locked down as `Account`.

[TypeScript Playground](https://www.typescriptlang.org/play?target=99&ssl=4&ssc=107&pln=4&pc=94#code/JYWwDg9gTgLgBAbzgYygUwIYzQdQwG3zRgGF9g0A7GAGhQFcBnGCEOmATzDTgEFlkEetTgBfOADMorOAHIAbhRCyAUKEixEcEBmCVKxMZOkg5itCAD0yABa7KjVSsEP4AbQwCh1ALpwAvHAAFBgA7rrwQaF6ACYQoXAYjImUHACUAHTENmjo9CAZ6ACO9GjMQUgg2RAxAFxy2QD6xaXM-ILCMI5iaWmJyW7t3jA+Ks4QrijkVPCBqJjYeITEZBTUFXAqcIlenXRbKHZ69Tp6BrQHMFAYDhow9chMLCBBUbHx-SnpWTA5eSBpGgqURpMYuZhwOyMGwBRLhYDwZDTagZRhUGIAFWuDk8MGAEwqlwg9VkAAYAB4YACsAgAzMhSbSAJxMgAsABEAEJUgBGpJiTN4VLQAFEYuyAIykkgYHkYTmkgAcEtpADYAOyK3gkWRA7byAileoSyjAtJAA)

**Comment by paro-paro** [comment]
Ups, sorry! Thanks a lot!

**Comment by egemon** [comment]
Had same issue. 
Fixed it with passing explicit Type to Wallet generic:

```
import { Account, Chain, PublicClient, Transport, WalletClient } from 'viem';

interface ExtendedWalletClient extends WalletClient<Transport, Chain, Account> {
  waitForTransactionReceipt: PublicClient['waitForTransactionReceipt'];
}
```
